### ISSUE TITLE
Jenkins build failing on zoidberg at 'Publish coverage to GitHub'

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro-wsd#89]
The DKPro WSD package is now successfully building on zoidberg's Jenkins instance, except for a final step:

```
[GitHub PR Status] start
ERROR: Build step failed with exception
java.lang.UnsupportedOperationException: Can't find ghprbPullId or scmVars in build variables!
	at com.github.terma.jenkins.githubprcoveragestatus.PrIdAndUrlUtils.getPrId(PrIdAndUrlUtils.java:73)
	at com.github.terma.jenkins.githubprcoveragestatus.CompareCoverageAction.perform(CompareCoverageAction.java:131)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1074)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1905)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Build step 'Publish coverage to GitHub' marked build as failure
Sending e-mails to: dkpro-wsd-developers@googlegroups.com
Finished: FAILURE
```

@reckart, can you advise?  Is there something that needs to be updated on Jenkins?

**Comment by logological** [comment]
Any update on this, @reckart?

**Comment by reckart** [comment]
I think the build config should be changed to not try to push the coverage status.

**Comment by reckart** [comment]
I have removed the setting and triggered a built. Let's see...

**Comment by reckart** [comment]
That said, if the build doesn't require special resources from the CI server and if it takes a reasonably amount of time, then switching to GitHub actions might be a good direction.

**Comment by logological** [comment]
Well, the build seems to have completed successfully, so I guess this particular issue is fixed.  Thanks!  I don't know anything about GitHub Actions so can't comment on your last suggestion.
